version: 2.1
jobs:
  build:
    docker: 
      - image: circleci/openjdk:8-jdk # the primary container, where your job's commands are run
    steps:
      - checkout # check out the code in the project directory
      - run: echo "hello world" # run the `echo` command
      - run: ls -l
      - run:
          name: Install jFrog CLI
          command: curl -fL https://getcli.jfrog.io | sh
          
      - run:
          name: Config
          command: |
            mvn -version
            gradle -version
            
      - run:
          name: Config
          command: |
            ./jfrog rt config --url $ARTIFACTORY_URL --user $ARTIFACTORY_USER --apikey $ARTIFACTORY_APIKEY --interactive=false
            ./jfrog rt c show
            
      - run:
          name: Gradle install 
          command: |
            ./jfrog rt gradle clean artifactoryPublish -b gradle.conf  --build-name=circleci-gradle-artifactory --build-number=$CIRCLE_BUILD_NUM

      - run:
          name: Collect the environment variables 
          command: |
            ./jfrog rt bce circleci-gradle-artifactory $CIRCLE_BUILD_NUM 
                  
      - run:
          name: Add sonar
          command: |
            ./jfrog rt sp "gradle-dev-local/org/jfrog/example/gradle/" "qulity.gate.sonarUrl=http://ip:9000/dashboard/index/circleci-gradle-artifactory"
        
      - run:
          name: Add properties
          command: |
            ./jfrog rt sp "gradle-dev-local/org/jfrog/example/gradle/" "deploy.tool=ansible"
            ./jfrog rt sp "gradle-dev-local/org/jfrog/example/gradle/" "ip=127.0.0.1"
            
      - run:
          name: Pass the build information to Artifactory   
          command: |
            ./jfrog rt bp circleci-gradle-artifactory $CIRCLE_BUILD_NUM 
   
      - run:
          name: Promote  
          command: |
            ./jfrog rt bpr circleci-gradle-artifactory $CIRCLE_BUILD_NUM gradle-pro-local
  
      - run:
          name: Xray Scan 
          command: |
            ./jfrog rt bs circleci-gradle-artifactory $CIRCLE_BUILD_NUM --fail=false
